spring.application.name=product-service

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000

####################################################
# JPA
####################################################
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

####################################################
# ACTUATOR
####################################################
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

####################################################
# LOGGING
####################################################
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.learn=DEBUG

####################################################
# SERVER
####################################################
server.port=8080

####################################################
# AWS
####################################################
aws.sns.topic.arn=arn:aws:sns:ap-southeast-1:132851953521:SpringBootProductTopic